version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: lemp-containers-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lempdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    image: lemp-backend:latest
    container_name: lemp-containers-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: lemp-frontend:latest
    container_name: lemp-containers-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db-data:
