services:
  db:
    image: mysql:8.0
    container_name: lemp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: abdullatifk/lemp-backend:1.0.0
    container_name: lemp-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: abdullatifk/lemp-frontend:1.0.0
    container_name: lemp-frontend
    restart: always
    ports:
      - "8080:80"

volumes:
  db_data:
