name: CI/CD for Containerized LEMP App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build & Push Backend
      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/containerized-lemp-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/containerized-lemp-backend:latest

      # Build & Push Frontend
      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/containerized-lemp-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/containerized-lemp-frontend:latest

      # Optional: Test Backend API
      - name: Test Backend API
        run: |
          docker run -d --name temp-backend -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/containerized-lemp-backend:latest
          sleep 10
          curl -f http://localhost:8000/api
          docker stop temp-backend
          docker rm temp-backend


